"""Test for CLI module."""

from unittest.mock import MagicMock, patch

import pytest
from folio_sync.shell.cli import main
from folio_sync.shell.db import SQLiteDocumentRepository


@pytest.fixture
def mock_conn():
    conn = MagicMock()
    conn.cursor.return_value = MagicMock()
    return conn


def test_upsert_document_new(mock_conn):
    """Test upserting a completely new document."""
    cur = mock_conn.cursor.return_value
    cur.fetchone.return_value = None

    repo = SQLiteDocumentRepository(mock_conn)
    content = "---\ntitle: Test\n---\nBody"
    changed = repo.upsert_document("test.md", content)

    assert changed is True
    assert cur.execute.call_count >= 3


def test_upsert_document_unchanged(mock_conn):
    """Test upserting an unchanged document."""
    cur = mock_conn.cursor.return_value
    # mock existing hash
    content = "---\ntitle: Test\n---\nBody"

    # Needs to match the hash generated by the prepare_document
    from folio_sync.core.indexer import prepare_document

    doc = prepare_document("test.md", content)
    cur.fetchone.return_value = [doc["content_hash"]]

    repo = SQLiteDocumentRepository(mock_conn)
    changed = repo.upsert_document("test.md", content)

    assert changed is False


@patch("folio_sync.shell.cli.connect_db")
@patch("folio_sync.shell.cli.init_db")
@patch("folio_sync.shell.cli.SQLiteDocumentRepository")
def test_main_runs_correctly(mock_repo_cls, mock_init_db, mock_connect_db, tmp_path):
    """Test the main CLI flow."""
    import sys

    # Setup a dummy directory and file
    data_dir = tmp_path / "data"
    data_dir.mkdir()
    test_md = data_dir / "test.md"
    test_md.write_text("Hello")

    db_path = tmp_path / "folio.sqlite"

    mock_conn = MagicMock()
    # To mock the context manager
    mock_connect_db.return_value.__enter__.return_value = mock_conn
    mock_cur = mock_conn.cursor.return_value
    mock_cur.fetchone.return_value = None
    
    mock_repo_instance = MagicMock()
    mock_repo_instance.upsert_document.return_value = True
    mock_repo_cls.return_value = mock_repo_instance

    test_args = ["cli", str(data_dir), str(db_path)]
    with patch.object(sys, "argv", test_args):
        main()

    mock_init_db.assert_called_once_with(db_path)
    mock_connect_db.assert_called_once_with(db_path)
    mock_repo_cls.assert_called_once_with(mock_conn)
    mock_repo_instance.upsert_document.assert_called_once_with("test.md", "Hello")
    assert mock_conn.commit.called
